name: Create and publish changed packages
on:
  push:
    branches: ['master']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
        scope: '@theorchard'
    - uses: pnpm/action-setup@v1.2.1
      with:
        version: 5.17.2
    - run: pnpm install
    - run: pnpm root:deploy
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
